{{- range $h, $cluster := .Values.clusters }} 
#
# Cluster {{ $cluster }}
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-{{ $cluster }}
  labels:
    cluster: {{ $cluster }}
spec:
  destination:
    namespace: kad
    name: {{ $cluster }}
  source:
    path: helm
    repoURL: https://gitlab.com/6shore.net/kad.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}
