---
apiVersion: v1
kind: Service
metadata:
  name: kad
  annotations:
    prometheus.io/scrape: "{{ .Values.prometheus.enabled }}"
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  selector:
    app: kad
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kad
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: {{ required ".Values.image is required!" .Values.image }}
        command: ["/bin/kad", "--color", "$(COLOR)"]
        ports:
        - containerPort: 5000
        env:
        - name: CLUSTER
          value: {{ .Values.cluster }}
        - name: COLOR
          value: {{ .Values.color | quote }} #as the values contains a hash :D
        - name: REDIS_SERVER
          value: redis:6379
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
