{{ range $h, $cluster := .Values.clusters }}
---
# kad {{ $cluster }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: kad
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: helm
  destination:
    name: {{ $cluster }}
    namespace: {{ $.Values.namespace }}
  helm:
    values: |-
      cluster: {{ $cluster }}
      {{- toYaml $.Values.kad | nindent 6 }}
  syncPolicy:
    {{- if $.Values.autosync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
    - Validate=true
    - CreateNamespace=true
{{ end }}

# vim: filetype=gotexttmpl

