apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://gitlab.com/6shore.net/kad
    targetRevision: HEAD
    path: cluster
    helm:
      values: |
        clusters: 
        - c0
        - physical
        - vk8s-ce
        #- vk8s-re
        replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - Validate=true
   - CreateNamespace=true
