---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kad
spec:
  selector:
    app: kad
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kad
  namespace: kad
data:
  config.yml: |
    abc: 123
    password: datascript
  option.color: white
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: kad
type: Opaque
data:
  username: YWRtaW4=
  password: d29ya3Nob3BTRA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
  namespace: kad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kad
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: tomkukral/kad:ld19
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["/bin/kad", "--color", "$(COLOR)", "--user", "$(USERNAME)"]
        env:
        # static configuration from yaml
        - name: REDIS_SERVER
          value: redis:6379
        # configuraiton from downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # variable form configmap
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kad
              key: option.color
        # variables from secret
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /etc/kad/
      volumes:
      - name: config
        configMap:
          name: kad
          items:
          - key: config.yml
            path: config.yml
