---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kad
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kad
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-data
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 6379
