name: "Deploy to master"
# Only one job in concurrency group can be run at the same time
concurrency:
  group: master-${{ github.ref }}
  # cancel-in-progress: true

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force:
        description: "Ignore changes and force deploy"
        type: string
        default: "true"
      pr-number:
        description: "PR to build preview environment for"
        type: string
      runs-on:
        description: "Ignore changes and force deploy"
        type: string
        default: "self-hosted"
jobs:
  build-backend-docker-image:
    uses: ./.github/workflows/reusable-backend-build-docker-v2.yaml
    with:
      docker-image-name: xbery-ops/kad
      force: true
      docker-context: ./
      dockerfile: ./Dockerfile
      runs-on: ${{ github.event.inputs.runs-on || 'ubuntu-latest' }}
    secrets: inherit
  publish:
    needs: [ build-backend-docker-image ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:   
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Set SHA env
        run: echo "GITHUB_SHA_SHORT=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c 1-8)" >> $GITHUB_ENV  
      
      - uses: actions/checkout@v3
        with:
          repository: 'bery/argocd-preview-environments-deployments'
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: main

      - run: ls -la

      - run: touch values.yaml

      - run: yq e -i '.image = "706337823207.dkr.ecr.eu-central-1.amazonaws.com/xbery-ops/kad:sha8-${{ env.GITHUB_SHA_SHORT }}"' values.yaml

      - run: cat values.yaml

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Release sha-${{ env.GITHUB_SHA_SHORT }}'